### ISSUE TITLE
graphviz isn't working

### ISSUE THREAD

**Issue by ChrisOboe** [felixvanoost/jekyll-kroki#21]
Hi, 

i can't get it to work with graphviz. 

here is the relevant part of my file:
```
'''plantuml
participant Jekyll
participant Kroki #MediumSpringGreen

Jekyll -> Kroki: Encoded diagram description
Kroki --> Jekyll: Rendered diagram in SVG format
'''

'''graphviz
digraph "test" {
 a -> b
}
'''
```

i replaced the backticks ` with the ' because otherwise github issues messes the rendering up. 

i get the following log:
```
[jekyll-kroki] Rendered 1 diagrams using Kroki instance at 'https://kroki.io/'
                    done in 0.784 seconds.
```

the plantuml part is rendered correctly, the graphviz part isn't rendered at all. i only see the plaintext. 
I'm not sure if i'm doing something wrong or if this is a bug.

**Comment by ChrisOboe** [comment]
i investigated this a bit further. it seems jekyll generates different html output for plantuml and graphviz. 
for plantuml i get 
```
<pre>
<code class="language-plantuml">
...
```

for graphviz i get
```
<div class="language-graphviz highligter-rogue">
...
```

i'm neither a ruby dev nor a experienced jekyll user so i'm not sure whats the proper way of fixing would be.

**Comment by felixvanoost** [comment]
I was able to repoduce this bug and also confirm that your PR #22 fixed it:

```shell
[jekyll-kroki] Rendered 2 diagrams using Kroki instance at 'https://kroki.io/'
                    done in 0.338 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
```

![Screenshot 2024-02-26 231723](https://github.com/felixvanoost/jekyll-kroki/assets/10233016/5d75a30d-2e21-4da9-ad89-f26e31369d51)

Thanks again and happy to hear that someone else found this plugin useful!
